name: Terraform
on: 
  push:
    branches:
      - 'deploy/*'

jobs:
  plan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: technote-space/get-diff-action@v4
        with:
          SEPARATOR: ','
      - run: echo $GIT_DIFF | tr , \\n | xargs -n 1 dirname | uniq | xargs -n 1 bash -c 'cd $0 && echo $0 && terraform init && terraform plan'
  apply:
    runs-on: ubuntu-20.04
    needs: plan
    environment: apply
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: echo apply
